#pragma once

#include <iostream>
#include <string>

#include "../Common/Color.h"
#include "../Common/UnicodeGlyphs.h"
#include "../Common/Sprite.h"


using namespace std;

inline string Rayquaza() {
    string sprite;
    const string RESET = "\033[0m";
    char ENDL = '\n';

    const string FG1 = "\033[38;2;0;0;0m";
    const string FG2 = "\033[38;2;41;82;65m";
    const string FG3 = "\033[38;2;90;189;139m";
    const string FG4 = "\033[38;2;148;222;180m";
    const string FG5 = "\033[38;2;74;131;115m";
    const string FG6 = "\033[38;2;131;98;49m";
    const string FG7 = "\033[38;2;197;164;0m";
    const string FG8 = "\033[38;2;246;222;0m";
    const string FG9 = "\033[38;2;230;82;115m";
    const string FG10 = "\033[38;2;156;41;82m";
    const string FG11 = "\033[38;2;115;41;57m";
    const string FG12 = "\033[38;2;189;98;139m";
    const string FG13 = "\033[38;2;255;255;255m";
    const string FG14 = "\033[38;2;222;213;238m";

    const string BG1 = "\033[48;2;0;0;0m";
    const string BG2 = "\033[48;2;41;82;65m";
    const string BG3 = "\033[48;2;90;189;139m";
    const string BG4 = "\033[48;2;148;222;180m";
    const string BG5 = "\033[48;2;74;131;115m";
    const string BG6 = "\033[48;2;131;98;49m";
    const string BG7 = "\033[48;2;197;164;0m";
    const string BG8 = "\033[48;2;246;222;0m";
    const string BG9 = "\033[48;2;230;82;115m";
    const string BG10 = "\033[48;2;156;41;82m";
    const string BG11 = "\033[48;2;115;41;57m";
    const string BG12 = "\033[48;2;189;98;139m";
    const string BG13 = "\033[48;2;255;255;255m";
    const string BG14 = "\033[48;2;222;213;238m";

    sprite += FG1 + BG1 + repeat_pixel(55);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(49);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG3 + BG4 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(48);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(18);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(25);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(6);    sprite += FG4 + BG2 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(15);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(25);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(6);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(11);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(28);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(8);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(3);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(29);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG2 + BG6 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG7 + BG7 + repeat_pixel(1);    sprite += FG7 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(2);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG5 + BG1 + repeat_pixel(2);    sprite += FG1 + BG1 + repeat_pixel(30);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG8 + BG3 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(3);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG2 + BG7 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(31);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(5);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG7 + BG6 + repeat_pixel(1);    sprite += FG5 + BG7 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(2);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(28);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(2);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG8 + BG5 + repeat_pixel(1);    sprite += FG1 + BG9 + repeat_pixel(1);    sprite += FG3 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG5 + BG9 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG7 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG7 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG10 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(25);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG3 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG11 + BG1 + repeat_pixel(2);    sprite += FG9 + BG11 + repeat_pixel(1);    sprite += FG9 + BG12 + repeat_pixel(1);    sprite += FG12 + BG12 + repeat_pixel(1);    sprite += FG12 + BG9 + repeat_pixel(1);    sprite += FG11 + BG9 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG3 + BG1 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG7 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG10 + BG2 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(24);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += FG9 + BG10 + repeat_pixel(1);    sprite += FG10 + BG12 + repeat_pixel(1);    sprite += FG12 + BG12 + repeat_pixel(1);    sprite += FG12 + BG11 + repeat_pixel(1);    sprite += FG11 + BG5 + repeat_pixel(1);    sprite += FG9 + BG5 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG1 + BG9 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG3 + BG1 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG7 + BG7 + repeat_pixel(1);    sprite += FG5 + BG7 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(24);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += FG9 + BG1 + repeat_pixel(1);    sprite += FG10 + BG1 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(2);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG9 + BG5 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(2);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG3 + BG1 + repeat_pixel(2);    sprite += FG1 + BG5 + repeat_pixel(2);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG3 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG7 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG10 + BG5 + repeat_pixel(2);    sprite += FG11 + BG5 + repeat_pixel(2);    sprite += FG1 + BG1 + repeat_pixel(19);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG11 + BG3 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(5);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG5 + BG7 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG5 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(4);    sprite += FG1 + BG1 + repeat_pixel(19);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(6);    sprite += FG2 + BG4 + repeat_pixel(1);    sprite += FG5 + BG4 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG5 + BG2 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG7 + BG5 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG4 + BG3 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(3);    sprite += FG11 + BG10 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(18);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG4 + BG4 + repeat_pixel(1);    sprite += FG4 + BG3 + repeat_pixel(1);    sprite += FG3 + BG8 + repeat_pixel(1);    sprite += FG3 + BG7 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG11 + BG2 + repeat_pixel(1);    sprite += FG2 + BG11 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG1 + BG13 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG9 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(2);    sprite += FG3 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG10 + BG10 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG5 + BG7 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(13);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG3 + BG4 + repeat_pixel(1);    sprite += FG4 + BG4 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG7 + BG8 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(2);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG2 + BG2 + repeat_pixel(1);    sprite += FG11 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG14 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG5 + BG14 + repeat_pixel(1);    sprite += FG3 + BG1 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG5 + BG3 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(4);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(3);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(11);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG2 + BG2 + repeat_pixel(1);    sprite += FG4 + BG4 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG8 + BG3 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(4);    sprite += FG10 + BG1 + repeat_pixel(3);    sprite += FG1 + BG1 + repeat_pixel(9);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG13 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(2);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG1 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(8);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG7 + BG5 + repeat_pixel(1);    sprite += FG5 + BG7 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(10);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG3 + BG8 + repeat_pixel(1);    sprite += FG3 + BG7 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG11 + BG9 + repeat_pixel(4);    sprite += FG1 + BG11 + repeat_pixel(2);    sprite += FG1 + BG1 + repeat_pixel(6);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG3 + BG14 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(11);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG1 + BG11 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG7 + BG5 + repeat_pixel(1);    sprite += FG4 + BG3 + repeat_pixel(1);    sprite += FG3 + BG4 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG11 + BG3 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(5);    sprite += FG9 + BG3 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(2);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG3 + BG4 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG5 + BG7 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(16);    sprite += FG5 + BG10 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG1 + BG11 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(4);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(4);    sprite += FG5 + BG7 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG4 + BG4 + repeat_pixel(2);    sprite += FG3 + BG4 + repeat_pixel(3);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG3 + BG8 + repeat_pixel(2);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG8 + BG7 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(17);    sprite += FG11 + BG1 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG10 + repeat_pixel(1);    sprite += FG5 + BG11 + repeat_pixel(1);    sprite += FG11 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG7 + BG1 + repeat_pixel(1);    sprite += FG5 + BG7 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG5 + BG11 + repeat_pixel(1);    sprite += FG3 + BG9 + repeat_pixel(4);    sprite += FG3 + BG10 + repeat_pixel(1);    sprite += FG3 + BG11 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG3 + BG7 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG7 + repeat_pixel(1);    sprite += FG7 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(21);    sprite += FG5 + BG10 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(9);    sprite += FG5 + BG5 + repeat_pixel(8);    sprite += FG2 + BG5 + repeat_pixel(2);    sprite += FG1 + BG1 + repeat_pixel(27);    sprite += FG11 + BG1 + repeat_pixel(1);    sprite += FG5 + BG11 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(10);    sprite += FG5 + BG10 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(4);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG10 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(37);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(55);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(55);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(55);    sprite += RESET + ENDL;

    return sprite;
}
