#pragma once

#include <iostream>
#include <string>

#include "../Common/Color.h"
#include "../Common/UnicodeGlyphs.h"
#include "../Common/Sprite.h"

using namespace std;

inline string RayquazaShiny() {
    string sprite;
    const string RESET = "\033[0m";
    char ENDL = '\n';

    const string FG1 = "\033[38;2;0;0;0m";
    const string FG2 = "\033[38;2;32;41;32m";
    const string FG3 = "\033[38;2;115;123;115m";
    const string FG4 = "\033[38;2;148;164;156m";
    const string FG5 = "\033[38;2;74;82;74m";
    const string FG6 = "\033[38;2;24;24;24m";
    const string FG7 = "\033[38;2;197;148;98m";
    const string FG8 = "\033[38;2;230;213;0m";
    const string FG9 = "\033[38;2;255;246;0m";
    const string FG10 = "\033[38;2;246;98;98m";
    const string FG11 = "\033[38;2;156;41;41m";
    const string FG12 = "\033[38;2;123;65;49m";
    const string FG13 = "\033[38;2;172;98;115m";
    const string FG14 = "\033[38;2;255;255;255m";
    const string FG15 = "\033[38;2;222;230;230m";

    const string BG1 = "\033[48;2;0;0;0m";
    const string BG2 = "\033[48;2;32;41;32m";
    const string BG3 = "\033[48;2;115;123;115m";
    const string BG4 = "\033[48;2;148;164;156m";
    const string BG5 = "\033[48;2;74;82;74m";
    const string BG6 = "\033[48;2;24;24;24m";
    const string BG7 = "\033[48;2;197;148;98m";
    const string BG8 = "\033[48;2;230;213;0m";
    const string BG9 = "\033[48;2;255;246;0m";
    const string BG10 = "\033[48;2;246;98;98m";
    const string BG11 = "\033[48;2;156;41;41m";
    const string BG12 = "\033[48;2;123;65;49m";
    const string BG13 = "\033[48;2;172;98;115m";
    const string BG14 = "\033[48;2;255;255;255m";
    const string BG15 = "\033[48;2;222;230;230m";

    sprite += FG1 + BG1 + repeat_pixel(55);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(49);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG3 + BG4 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(48);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(18);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(25);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(6);    sprite += FG4 + BG2 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(15);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(25);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(6);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(10);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(27);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(8);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(3);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(28);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG2 + BG7 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG6 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG8 + BG8 + repeat_pixel(1);    sprite += FG8 + BG2 + repeat_pixel(1);    sprite += FG6 + BG3 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(2);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(2);    sprite += FG1 + BG1 + repeat_pixel(30);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(5);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG9 + BG3 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(3);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG2 + BG8 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(31);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG6 + BG3 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG6 + BG3 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(5);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG8 + BG7 + repeat_pixel(1);    sprite += FG5 + BG8 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(2);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(28);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(2);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG9 + BG5 + repeat_pixel(1);    sprite += FG6 + BG10 + repeat_pixel(1);    sprite += FG3 + BG6 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG5 + BG10 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG7 + BG5 + repeat_pixel(1);    sprite += FG8 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG8 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG11 + repeat_pixel(1);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(24);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG2 + BG6 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG3 + BG6 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG12 + BG1 + repeat_pixel(1);    sprite += FG12 + BG6 + repeat_pixel(1);    sprite += FG10 + BG12 + repeat_pixel(1);    sprite += FG10 + BG13 + repeat_pixel(1);    sprite += FG13 + BG13 + repeat_pixel(1);    sprite += FG13 + BG10 + repeat_pixel(1);    sprite += FG12 + BG10 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG3 + BG1 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG8 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG11 + BG2 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(23);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG10 + BG11 + repeat_pixel(1);    sprite += FG11 + BG13 + repeat_pixel(1);    sprite += FG13 + BG13 + repeat_pixel(1);    sprite += FG13 + BG12 + repeat_pixel(1);    sprite += FG12 + BG5 + repeat_pixel(1);    sprite += FG10 + BG5 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG1 + BG10 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG3 + BG6 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG8 + BG8 + repeat_pixel(1);    sprite += FG5 + BG8 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(23);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += FG10 + BG1 + repeat_pixel(1);    sprite += FG11 + BG6 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG2 + repeat_pixel(2);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG10 + BG5 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG3 + BG6 + repeat_pixel(2);    sprite += FG1 + BG5 + repeat_pixel(2);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG3 + BG6 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG8 + BG5 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG11 + BG5 + repeat_pixel(2);    sprite += FG12 + BG5 + repeat_pixel(2);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(18);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG12 + BG3 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(5);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG5 + BG8 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG5 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(4);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(18);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(6);    sprite += FG2 + BG4 + repeat_pixel(1);    sprite += FG5 + BG4 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG6 + BG2 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG5 + BG2 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG8 + BG5 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG4 + BG3 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(3);    sprite += FG12 + BG11 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(17);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG4 + BG4 + repeat_pixel(1);    sprite += FG4 + BG3 + repeat_pixel(1);    sprite += FG3 + BG9 + repeat_pixel(1);    sprite += FG3 + BG8 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG12 + BG2 + repeat_pixel(1);    sprite += FG2 + BG12 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG6 + BG14 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG10 + BG5 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(1);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(2);    sprite += FG3 + BG6 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG2 + BG6 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG6 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG11 + BG11 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG5 + BG8 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG1 + BG5 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(13);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG3 + BG4 + repeat_pixel(1);    sprite += FG4 + BG4 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG8 + BG9 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG6 + repeat_pixel(2);    sprite += FG6 + BG2 + repeat_pixel(1);    sprite += FG2 + BG2 + repeat_pixel(1);    sprite += FG12 + BG2 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG15 + BG6 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG5 + BG15 + repeat_pixel(1);    sprite += FG3 + BG6 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG2 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG5 + BG3 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(3);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(11);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG2 + BG2 + repeat_pixel(1);    sprite += FG4 + BG4 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG9 + BG3 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG11 + BG1 + repeat_pixel(3);    sprite += FG6 + BG1 + repeat_pixel(3);    sprite += FG1 + BG1 + repeat_pixel(6);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG14 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(2);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG6 + repeat_pixel(1);    sprite += FG2 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG8 + BG5 + repeat_pixel(1);    sprite += FG5 + BG8 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(9);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG3 + BG9 + repeat_pixel(1);    sprite += FG3 + BG8 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG12 + BG10 + repeat_pixel(4);    sprite += FG1 + BG12 + repeat_pixel(2);    sprite += FG1 + BG1 + repeat_pixel(6);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG3 + BG15 + repeat_pixel(1);    sprite += FG6 + BG2 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG2 + BG6 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(10);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG6 + BG2 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG6 + BG12 + repeat_pixel(1);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(6);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG8 + BG5 + repeat_pixel(1);    sprite += FG4 + BG3 + repeat_pixel(1);    sprite += FG3 + BG4 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(1);    sprite += FG12 + BG3 + repeat_pixel(1);    sprite += FG5 + BG3 + repeat_pixel(5);    sprite += FG10 + BG3 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG1 + BG2 + repeat_pixel(1);    sprite += FG1 + BG3 + repeat_pixel(2);    sprite += FG2 + BG3 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG3 + BG4 + repeat_pixel(1);    sprite += FG6 + BG3 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG5 + BG8 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(15);    sprite += FG5 + BG11 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG6 + BG5 + repeat_pixel(1);    sprite += FG1 + BG12 + repeat_pixel(1);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(3);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG5 + BG8 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG2 + BG6 + repeat_pixel(1);    sprite += FG6 + BG3 + repeat_pixel(1);    sprite += FG4 + BG4 + repeat_pixel(2);    sprite += FG3 + BG4 + repeat_pixel(3);    sprite += FG3 + BG3 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(1);    sprite += FG2 + BG6 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG3 + BG9 + repeat_pixel(2);    sprite += FG3 + BG3 + repeat_pixel(2);    sprite += FG9 + BG8 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(2);    sprite += FG7 + BG6 + repeat_pixel(1);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(16);    sprite += FG12 + BG6 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(1);    sprite += FG2 + BG6 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG5 + BG11 + repeat_pixel(1);    sprite += FG5 + BG12 + repeat_pixel(1);    sprite += FG12 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(2);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(4);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG8 + BG6 + repeat_pixel(1);    sprite += FG5 + BG8 + repeat_pixel(1);    sprite += FG6 + BG6 + repeat_pixel(1);    sprite += FG5 + BG12 + repeat_pixel(1);    sprite += FG3 + BG10 + repeat_pixel(4);    sprite += FG3 + BG11 + repeat_pixel(1);    sprite += FG3 + BG12 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG6 + BG2 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG3 + BG8 + repeat_pixel(1);    sprite += FG3 + BG5 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG8 + repeat_pixel(1);    sprite += FG8 + BG6 + repeat_pixel(1);    sprite += FG5 + BG1 + repeat_pixel(1);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(19);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG5 + BG11 + repeat_pixel(1);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG2 + BG6 + repeat_pixel(1);    sprite += FG5 + BG6 + repeat_pixel(1);    sprite += FG1 + BG6 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(4);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += FG6 + BG1 + repeat_pixel(2);    sprite += FG5 + BG5 + repeat_pixel(8);    sprite += FG2 + BG5 + repeat_pixel(2);    sprite += FG6 + BG1 + repeat_pixel(3);    sprite += FG1 + BG1 + repeat_pixel(24);    sprite += FG12 + BG6 + repeat_pixel(1);    sprite += FG5 + BG12 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(7);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(9);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG5 + BG11 + repeat_pixel(1);    sprite += FG2 + BG5 + repeat_pixel(4);    sprite += FG5 + BG5 + repeat_pixel(1);    sprite += FG5 + BG2 + repeat_pixel(1);    sprite += FG11 + BG6 + repeat_pixel(1);    sprite += FG6 + BG1 + repeat_pixel(1);    sprite += FG1 + BG1 + repeat_pixel(36);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(11);    sprite += FG6 + BG1 + repeat_pixel(6);    sprite += FG1 + BG1 + repeat_pixel(38);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(55);    sprite += RESET + ENDL;
    sprite += FG1 + BG1 + repeat_pixel(55);    sprite += RESET + ENDL;

    return sprite;
}
